eureka.client.enabled=false

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://payment-db:5432/payment_db}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

course.service.url=${COURSE_SERVICE_URL:http://course-service:8083}
